{ isLaptop, pkgs, unstable, unstable-small, lpkgs }:

[
  lpkgs.dmenumount
  lpkgs.dmenuumount
  pkgs.kmenuedit
  #pkgs.mumble
  #pkgs.nethack
  #pkgs.obs-studio
  lpkgs.python-with-my-packages
  unstable-small.discord
  unstable-small.multimc
  unstable.chromium
  unstable.jetbrains.idea-community
  unstable.qutebrowser
  unstable.runelite
  unstable.steam
  unstable.youtubeDL
  pkgs.arc-icon-theme
  pkgs.ascii
  pkgs.bazel
  pkgs.bc
  pkgs.bind
  pkgs.binutils-unwrapped
  pkgs.cryptsetup
  pkgs.deluge
  pkgs.dmenu
  pkgs.feh
  pkgs.ffmpeg-full
  pkgs.firefox # Eventually see home manager's programs.firefox.enableAdobeFlash, but that might delete bookmarks & settings.
  pkgs.fish
  pkgs.gcc
  pkgs.gimp
  pkgs.gmpc
  pkgs.gnome3.dconf
  pkgs.gnumake
  pkgs.gparted
  pkgs.gst-plugins-bad
  pkgs.gst-plugins-base
  pkgs.gst-plugins-good
  pkgs.gst-plugins-ugly
  pkgs.gstreamer
  pkgs.gvfs
  pkgs.htop
  pkgs.imagemagick
  pkgs.j
  pkgs.jmtpfs
  pkgs.lastpass-cli
  pkgs.libelf
  pkgs.libreoffice
  pkgs.librsvg
  pkgs.linuxHeaders
  pkgs.lxqt.lxqt-policykit
  pkgs.manpages
  pkgs.maven
  pkgs.mcomix
  pkgs.minecraft
  pkgs.mono
  pkgs.mpc_cli
  pkgs.mpd
  pkgs.nix-prefetch-git
  pkgs.p7zip
  pkgs.pavucontrol
  pkgs.polkit_gnome
  pkgs.pv
  pkgs.qt59.full
  pkgs.rustup
  pkgs.shared_mime_info
  pkgs.stdmanpages
  pkgs.sxhkd
  pkgs.thefuck
  pkgs.thunderbird
  pkgs.tor-browser-bundle-bin
  pkgs.trayer
  pkgs.unzip
  pkgs.vlc
  pkgs.vorbisTools
  pkgs.wget
  pkgs.xclip
  pkgs.xdotool
  pkgs.xfce.terminal
  pkgs.xfce.thunar
  pkgs.xfce.thunar-volman
  pkgs.xfce.tumbler
  pkgs.xorg.xev
  pkgs.xorg.xkill
  pkgs.xpdf
  pkgs.xzoom
  pkgs.zip
] ++ (if isLaptop then [
  pkgs.connman
] else [])
